/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * A loan calculator component.
     */
    interface NvqLoanCalculator {
        /**
          * The AmortizationPeriod label.
         */
        "amortizationPeriodLabel"?: string;
        /**
          * The heading for CALCULATOR section.
         */
        "calculatorHeading"?: string;
        /**
          * The Down Payment label.
         */
        "downPaymentLabel"?: string;
        /**
          * The heading for EXAMPLES section.
         */
        "examplesHeading"?: string;
        /**
          * The Interest Rate label.
         */
        "interestRateLabel"?: string;
        /**
          * The monthly payment footnote.
         */
        "monthlyPaymentDisclaimer"?: string;
        /**
          * The monthly payment label.
         */
        "monthlyPaymentLabel"?: string;
        /**
          * The Total Amount label.
         */
        "totalAmountLabel"?: string;
    }
}
declare global {
    /**
     * A loan calculator component.
     */
    interface HTMLNvqLoanCalculatorElement extends Components.NvqLoanCalculator, HTMLStencilElement {
    }
    var HTMLNvqLoanCalculatorElement: {
        prototype: HTMLNvqLoanCalculatorElement;
        new (): HTMLNvqLoanCalculatorElement;
    };
    interface HTMLElementTagNameMap {
        "nvq-loan-calculator": HTMLNvqLoanCalculatorElement;
    }
}
declare namespace LocalJSX {
    /**
     * A loan calculator component.
     */
    interface NvqLoanCalculator {
        /**
          * The AmortizationPeriod label.
         */
        "amortizationPeriodLabel"?: string;
        /**
          * The heading for CALCULATOR section.
         */
        "calculatorHeading"?: string;
        /**
          * The Down Payment label.
         */
        "downPaymentLabel"?: string;
        /**
          * The heading for EXAMPLES section.
         */
        "examplesHeading"?: string;
        /**
          * The Interest Rate label.
         */
        "interestRateLabel"?: string;
        /**
          * The monthly payment footnote.
         */
        "monthlyPaymentDisclaimer"?: string;
        /**
          * The monthly payment label.
         */
        "monthlyPaymentLabel"?: string;
        /**
          * The Total Amount label.
         */
        "totalAmountLabel"?: string;
    }
    interface IntrinsicElements {
        "nvq-loan-calculator": NvqLoanCalculator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A loan calculator component.
             */
            "nvq-loan-calculator": LocalJSX.NvqLoanCalculator & JSXBase.HTMLAttributes<HTMLNvqLoanCalculatorElement>;
        }
    }
}
