/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NvqLoanCalculator {
        /**
          * The AmortizationPeriod label
         */
        "amortizationPeriodLabel": string;
        /**
          * The heading for CALCULATOR section
         */
        "calculatorHeading": string;
        /**
          * The description for lead copy
         */
        "description": string;
        /**
          * The Down Payment label
         */
        "downPaymentLabel": string;
        /**
          * Example 1 heading
         */
        "example1Heading": string;
        /**
          * Example 2 heading
         */
        "example2Heading": string;
        /**
          * The heading for EXAMPLES section
         */
        "examplesHeading": string;
        /**
          * The heading for lead copy
         */
        "heading": string;
        /**
          * /**   The interest rate footnote - used with Examples section (optional)
         */
        "interestRateFootnote": string;
        /**
          * The Interest Rate label
         */
        "interestRateLabel": string;
        /**
          * /**   The monthly payment footnote (optional)
         */
        "monthlyPaymentFootnote": string;
        /**
          * The monthly payment label
         */
        "monthlyPaymentLabel": string;
        /**
          * The Total Amount label
         */
        "totalAmountLabel": string;
    }
}
declare global {
    interface HTMLNvqLoanCalculatorElement extends Components.NvqLoanCalculator, HTMLStencilElement {
    }
    var HTMLNvqLoanCalculatorElement: {
        prototype: HTMLNvqLoanCalculatorElement;
        new (): HTMLNvqLoanCalculatorElement;
    };
    interface HTMLElementTagNameMap {
        "nvq-loan-calculator": HTMLNvqLoanCalculatorElement;
    }
}
declare namespace LocalJSX {
    interface NvqLoanCalculator {
        /**
          * The AmortizationPeriod label
         */
        "amortizationPeriodLabel"?: string;
        /**
          * The heading for CALCULATOR section
         */
        "calculatorHeading"?: string;
        /**
          * The description for lead copy
         */
        "description"?: string;
        /**
          * The Down Payment label
         */
        "downPaymentLabel"?: string;
        /**
          * Example 1 heading
         */
        "example1Heading"?: string;
        /**
          * Example 2 heading
         */
        "example2Heading"?: string;
        /**
          * The heading for EXAMPLES section
         */
        "examplesHeading"?: string;
        /**
          * The heading for lead copy
         */
        "heading"?: string;
        /**
          * /**   The interest rate footnote - used with Examples section (optional)
         */
        "interestRateFootnote"?: string;
        /**
          * The Interest Rate label
         */
        "interestRateLabel"?: string;
        /**
          * /**   The monthly payment footnote (optional)
         */
        "monthlyPaymentFootnote"?: string;
        /**
          * The monthly payment label
         */
        "monthlyPaymentLabel"?: string;
        /**
          * The Total Amount label
         */
        "totalAmountLabel"?: string;
    }
    interface IntrinsicElements {
        "nvq-loan-calculator": NvqLoanCalculator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nvq-loan-calculator": LocalJSX.NvqLoanCalculator & JSXBase.HTMLAttributes<HTMLNvqLoanCalculatorElement>;
        }
    }
}
